import { FeatureItems, Order } from "../types/order";
import { ObjectId } from 'mongodb'; // If using MongoDB
 export const mockOrderItems: FeatureItems[] = [
      {
    id: "pet-001",
    name: "Golden Retriever Puppy",
    price: 1200,
    imageUrl: "https://picsum.photos/id/237/300/400", // Dog image
    description: "Friendly and loves fetch!",
    discount: 0,
  },
  {
    id: "pet-003",
    name: "Parakeet (Blue)",
    price: 45,
    imageUrl: "https://picsum.photos/id/100/300/400", // Bird-like image
    discount: 0.1,
  },
  {
    id: "pet-004",
    name: "Holland Lop Rabbit",
    price: 150,
    imageUrl: "https://picsum.photos/id/400/300/400", // Rabbit-like image
    discount: 0.25,
  },
  {
    id: "pet-005",
    name: "Bearded Dragon",
    price: 90,
    imageUrl: "https://picsum.photos/id/500/300/400", // Reptile-like image
    discount: 0.3,
  },
  {
    id: "pet-006",
    name: "Pomeranian",
    price: 950,
    imageUrl: "https://picsum.photos/id/1025/300/400", // Small dog image
    discount: 0.4,
  },
    {
    id: "pet-001",
    name: "Golden Retriever Puppy",
    price: 1200,
    imageUrl: "https://picsum.photos/id/237/300/400", // Dog image
    description: "Friendly and loves fetch!",
    discount: 0.2,
  },
  {
    id: "pet-003",
    name: "Parakeet (Blue)",
    price: 45,
    imageUrl: "https://picsum.photos/id/100/300/400", // Bird-like image
    discount: 0.1,
  },
  {
    id: "pet-004",
    name: "Holland Lop Rabbit",
    price: 150,
    imageUrl: "https://picsum.photos/id/400/300/400", // Rabbit-like image
    discount: 0.25,
  },
  {
    id: "pet-005",
    name: "Bearded Dragon",
    price: 90,
    imageUrl: "https://picsum.photos/id/500/300/400", // Reptile-like image
    discount: 0.3,
  },
  {
    id: "pet-006",
    name: "Pomeranian",
    price: 950,
    imageUrl: "https://picsum.photos/id/1025/300/400", // Small dog image
    discount: 0.4,
  }
  ]

export const browseOrderItems: Order[] = 
[
  {
    id: new ObjectId(), // or "order-0001"
    name: "Premium Dog Food Order",
    price: 89.99,
    dateCreated: new Date('2024-01-15'),
    status: 'completed',
    description: "30kg bag of premium grain-free dog food",
    dateUpdated: new Date('2024-01-17'),
    imageUrls: ["https://picsum.photos/id/237/300/200", "https://picsum.photos/id/237/300/201"],
    discount: 0.15,
    isFeatured: true
  },
  {
    id: new ObjectId(),
    name: "Cat Tree Condo",
    price: 156.50,
    dateCreated: new Date('2024-02-03'),
    status: 'pending',
    description: "Large 5-tier cat tree with scratching posts",
    dateUpdated: new Date('2024-02-03'),
    imageUrls: ["https://picsum.photos/id/219/300/200"],
    discount: 0.0,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Aquarium Starter Kit",
    price: 220.00,
    dateCreated: new Date('2024-02-10'),
    status: 'fresh',
    description: "20 gallon aquarium with filter and lighting",
    dateUpdated: new Date('2024-02-10'),
    imageUrls: ["https://picsum.photos/id/100/300/200", "https://picsum.photos/id/101/300/200"],
    discount: 0.25,
    isFeatured: true
  },
  {
    id: new ObjectId(),
    name: "Bird Cage Deluxe",
    price: 189.75,
    dateCreated: new Date('2024-02-12'),
    status: 'cancelled',
    description: "Large wrought iron cage with stand",
    dateUpdated: new Date('2024-02-14'),
    imageUrls: ["https://picsum.photos/id/108/300/200"],
    discount: 0.1,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Small Animal Habitat",
    price: 75.25,
    dateCreated: new Date('2024-02-18'),
    status: 'completed',
    description: "Modular habitat for hamsters and gerbils",
    dateUpdated: new Date('2024-02-20'),
    imageUrls: ["https://picsum.photos/id/189/300/200"],
    discount: 0.05,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Premium Cat Litter",
    price: 45.99,
    dateCreated: new Date('2024-02-22'),
    status: 'pending',
    description: "Clumping silica gel litter, 4-pack",
    dateUpdated: new Date('2024-02-22'),
    imageUrls: ["https://picsum.photos/id/145/300/200"],
    discount: 0.0,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Dog Training Kit",
    price: 134.50,
    dateCreated: new Date('2024-02-25'),
    status: 'fresh',
    description: "Complete obedience training package",
    dateUpdated: new Date('2024-02-25'),
    imageUrls: ["https://picsum.photos/id/201/300/200"],
    discount: 0.3,
    isFeatured: true
  },
  {
    id: new ObjectId(),
    name: "Reptile Heating Lamp",
    price: 32.99,
    dateCreated: new Date('2024-02-28'),
    status: 'completed',
    description: "100W ceramic heat emitter",
    dateUpdated: new Date('2024-03-01'),
    imageUrls: ["https://picsum.photos/id/102/300/200"],
    discount: 0.15,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Premium Fish Food",
    price: 28.75,
    dateCreated: new Date('2024-03-02'),
    status: 'pending',
    description: "Variety pack for tropical fish",
    dateUpdated: new Date('2024-03-02'),
    imageUrls: ["https://picsum.photos/id/103/300/200"],
    discount: 0.0,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Pet Grooming Kit",
    price: 89.99,
    dateCreated: new Date('2024-03-05'),
    status: 'completed',
    description: "Professional grooming tools for dogs and cats",
    dateUpdated: new Date('2024-03-07'),
    imageUrls: ["https://picsum.photos/id/203/300/200"],
    discount: 0.2,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Automatic Feeder",
    price: 67.50,
    dateCreated: new Date('2024-03-08'),
    status: 'fresh',
    description: "Programmable pet feeder with portion control",
    dateUpdated: new Date('2024-03-08'),
    imageUrls: ["https://picsum.photos/id/218/300/200"],
    discount: 0.1,
    isFeatured: true
  },
  {
    id: new ObjectId(),
    name: "Orthopedic Dog Bed",
    price: 145.00,
    dateCreated: new Date('2024-03-12'),
    status: 'pending',
    description: "Memory foam bed for large breeds",
    dateUpdated: new Date('2024-03-12'),
    imageUrls: ["https://picsum.photos/id/202/300/200"],
    discount: 0.0,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Cat Water Fountain",
    price: 42.25,
    dateCreated: new Date('2024-03-15'),
    status: 'completed',
    description: "Stainless steel circulating water fountain",
    dateUpdated: new Date('2024-03-17'),
    imageUrls: ["https://picsum.photos/id/221/300/200"],
    discount: 0.35,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Bird Toys Bundle",
    price: 38.99,
    dateCreated: new Date('2024-03-18'),
    status: 'cancelled',
    description: "Assorted toys for parrots and large birds",
    dateUpdated: new Date('2024-03-19'),
    imageUrls: ["https://picsum.photos/id/107/300/200"],
    discount: 0.25,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Pet Carrier Backpack",
    price: 79.95,
    dateCreated: new Date('2024-03-20'),
    status: 'fresh',
    description: "Airline approved pet carrier backpack",
    dateUpdated: new Date('2024-03-20'),
    imageUrls: ["https://picsum.photos/id/222/300/200"],
    discount: 0.15,
    isFeatured: true
  },
  {
    id: new ObjectId(),
    name: "Dog Leash Set",
    price: 55.00,
    dateCreated: new Date('2024-03-22'),
    status: 'completed',
    description: "Retractable leash with harness",
    dateUpdated: new Date('2024-03-24'),
    imageUrls: ["https://picsum.photos/id/1024/300/200"],
    discount: 0.0,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Cat Scratching Post",
    price: 64.75,
    dateCreated: new Date('2024-03-25'),
    status: 'pending',
    description: "32-inch sisal scratching post with toys",
    dateUpdated: new Date('2024-03-25'),
    imageUrls: ["https://picsum.photos/id/225/300/200"],
    discount: 0.1,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Aquarium Decor Set",
    price: 87.30,
    dateCreated: new Date('2024-03-28'),
    status: 'completed',
    description: "Natural looking aquarium decorations",
    dateUpdated: new Date('2024-03-30'),
    imageUrls: ["https://picsum.photos/id/104/300/200"],
    discount: 0.4,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Pet First Aid Kit",
    price: 49.99,
    dateCreated: new Date('2024-04-01'),
    status: 'fresh',
    description: "Comprehensive pet emergency kit",
    dateUpdated: new Date('2024-04-01'),
    imageUrls: ["https://picsum.photos/id/231/300/200"],
    discount: 0.2,
    isFeatured: true
  },
  {
    id: new ObjectId(),
    name: "Dog Training Collar",
    price: 125.00,
    dateCreated: new Date('2024-04-03'),
    status: 'pending',
    description: "GPS tracking training collar",
    dateUpdated: new Date('2024-04-03'),
    imageUrls: ["https://picsum.photos/id/1025/300/200"],
    discount: 0.0,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Cat Window Perch",
    price: 39.95,
    dateCreated: new Date('2024-04-05'),
    status: 'completed',
    description: "Suction cup window bed for cats",
    dateUpdated: new Date('2024-04-07'),
    imageUrls: ["https://picsum.photos/id/230/300/200"],
    discount: 0.3,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Small Animal Wheel",
    price: 28.50,
    dateCreated: new Date('2024-04-08'),
    status: 'cancelled',
    description: "Silent spinner exercise wheel",
    dateUpdated: new Date('2024-04-09'),
    imageUrls: ["https://picsum.photos/id/191/300/200"],
    discount: 0.15,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Pet Stroller",
    price: 189.00,
    dateCreated: new Date('2024-04-10'),
    status: 'fresh',
    description: "All-terrain pet stroller for dogs and cats",
    dateUpdated: new Date('2024-04-10'),
    imageUrls: ["https://picsum.photos/id/1026/300/200"],
    discount: 0.25,
    isFeatured: true
  },
  {
    id: new ObjectId(),
    name: "Automatic Litter Box",
    price: 299.99,
    dateCreated: new Date('2024-04-12'),
    status: 'pending',
    description: "Self-cleaning automatic litter box",
    dateUpdated: new Date('2024-04-12'),
    imageUrls: ["https://picsum.photos/id/234/300/200"],
    discount: 0.0,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Dog Life Jacket",
    price: 45.75,
    dateCreated: new Date('2024-04-15'),
    status: 'completed',
    description: "Buoyancy vest for water activities",
    dateUpdated: new Date('2024-04-17'),
    imageUrls: ["https://picsum.photos/id/1027/300/200"],
    discount: 0.1,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Bird Feeding Station",
    price: 67.25,
    dateCreated: new Date('2024-04-18'),
    status: 'completed',
    description: "Multi-level feeding and watering station",
    dateUpdated: new Date('2024-04-20'),
    imageUrls: ["https://picsum.photos/id/109/300/200"],
    discount: 0.35,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Pet Camera",
    price: 159.00,
    dateCreated: new Date('2024-04-22'),
    status: 'fresh',
    description: "WiFi pet camera with treat dispenser",
    dateUpdated: new Date('2024-04-22'),
    imageUrls: ["https://picsum.photos/id/1028/300/200"],
    discount: 0.2,
    isFeatured: true
  },
  {
    id: new ObjectId(),
    name: "Cat Dental Care Kit",
    price: 34.99,
    dateCreated: new Date('2024-04-25'),
    status: 'pending',
    description: "Toothbrush and toothpaste for cats",
    dateUpdated: new Date('2024-04-25'),
    imageUrls: ["https://picsum.photos/id/235/300/200"],
    discount: 0.0,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Dog Puzzle Toys",
    price: 52.50,
    dateCreated: new Date('2024-04-28'),
    status: 'completed',
    description: "Interactive treat puzzle games",
    dateUpdated: new Date('2024-04-30'),
    imageUrls: ["https://picsum.photos/id/1029/300/200"],
    discount: 0.15,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Reptile Habitat Kit",
    price: 178.95,
    dateCreated: new Date('2024-05-01'),
    status: 'cancelled',
    description: "Complete desert habitat setup",
    dateUpdated: new Date('2024-05-02'),
    imageUrls: ["https://picsum.photos/id/98/300/200"],
    discount: 0.4,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Pet Heating Pad",
    price: 42.00,
    dateCreated: new Date('2024-05-03'),
    status: 'fresh',
    description: "Thermostat-controlled heating pad",
    dateUpdated: new Date('2024-05-03'),
    imageUrls: ["https://picsum.photos/id/192/300/200"],
    discount: 0.25,
    isFeatured: true
  },
  {
    id: new ObjectId(),
    name: "Dog Boots Set",
    price: 38.75,
    dateCreated: new Date('2024-05-05'),
    status: 'pending',
    description: "All-weather protective dog boots",
    dateUpdated: new Date('2024-05-05'),
    imageUrls: ["https://picsum.photos/id/1030/300/200"],
    discount: 0.1,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Cat Calming Diffuser",
    price: 29.99,
    dateCreated: new Date('2024-05-08'),
    status: 'completed',
    description: "Pheromone diffuser for anxious cats",
    dateUpdated: new Date('2024-05-10'),
    imageUrls: ["https://picsum.photos/id/236/300/200"],
    discount: 0.0,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Aquarium Filter System",
    price: 135.50,
    dateCreated: new Date('2024-05-12'),
    status: 'completed',
    description: "Canister filter for large aquariums",
    dateUpdated: new Date('2024-05-14'),
    imageUrls: ["https://picsum.photos/id/105/300/200"],
    discount: 0.3,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Pet Travel Bowl",
    price: 22.95,
    dateCreated: new Date('2024-05-15'),
    status: 'fresh',
    description: "Collapsible silicone travel bowls",
    dateUpdated: new Date('2024-05-15'),
    imageUrls: ["https://picsum.photos/id/1031/300/200"],
    discount: 0.15,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Dog Raincoat",
    price: 47.25,
    dateCreated: new Date('2024-05-18'),
    status: 'pending',
    description: "Waterproof reflective raincoat",
    dateUpdated: new Date('2024-05-18'),
    imageUrls: ["https://picsum.photos/id/1032/300/200"],
    discount: 0.2,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Cat Treat Variety Pack",
    price: 31.99,
    dateCreated: new Date('2024-05-20'),
    status: 'completed',
    description: "Assorted natural cat treats",
    dateUpdated: new Date('2024-05-22'),
    imageUrls: ["https://picsum.photos/id/237/300/200"],
    discount: 0.35,
    isFeatured: true
  },
  {
    id: new ObjectId(),
    name: "Bird Cage Cover",
    price: 28.50,
    dateCreated: new Date('2024-05-22'),
    status: 'cancelled',
    description: "Breathable cage cover for night time",
    dateUpdated: new Date('2024-05-23'),
    imageUrls: ["https://picsum.photos/id/110/300/200"],
    discount: 0.1,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Pet Scale",
    price: 89.00,
    dateCreated: new Date('2024-05-25'),
    status: 'fresh',
    description: "Digital pet weight scale",
    dateUpdated: new Date('2024-05-25'),
    imageUrls: ["https://picsum.photos/id/1033/300/200"],
    discount: 0.25,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Dog Cooling Mat",
    price: 36.75,
    dateCreated: new Date('2024-05-28'),
    status: 'pending',
    description: "Self-cooling gel mat for hot weather",
    dateUpdated: new Date('2024-05-28'),
    imageUrls: ["https://picsum.photos/id/1034/300/200"],
    discount: 0.0,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Cat Water Bowl",
    price: 24.99,
    dateCreated: new Date('2024-05-30'),
    status: 'completed',
    description: "Stainless steel anti-spill bowl",
    dateUpdated: new Date('2024-06-01'),
    imageUrls: ["https://picsum.photos/id/238/300/200"],
    discount: 0.4,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Pet GPS Tracker",
    price: 199.99,
    dateCreated: new Date('2024-06-02'),
    status: 'fresh',
    description: "Real-time location tracking collar",
    dateUpdated: new Date('2024-06-02'),
    imageUrls: ["https://picsum.photos/id/1035/300/200"],
    discount: 0.15,
    isFeatured: true
  },
  {
    id: new ObjectId(),
    name: "Aquarium Heater",
    price: 54.50,
    dateCreated: new Date('2024-06-05'),
    status: 'pending',
    description: "Submersible adjustable aquarium heater",
    dateUpdated: new Date('2024-06-05'),
    imageUrls: ["https://picsum.photos/id/106/300/200"],
    discount: 0.2,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Dog Seat Cover",
    price: 78.25,
    dateCreated: new Date('2024-06-08'),
    status: 'completed',
    description: "Waterproof car seat protector",
    dateUpdated: new Date('2024-06-10'),
    imageUrls: ["https://picsum.photos/id/1036/300/200"],
    discount: 0.3,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Catnip Toys Bundle",
    price: 33.99,
    dateCreated: new Date('2024-06-12'),
    status: 'completed',
    description: "Assorted organic catnip toys",
    dateUpdated: new Date('2024-06-14'),
    imageUrls: ["https://picsum.photos/id/239/300/200"],
    discount: 0.1,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Small Animal Playpen",
    price: 45.00,
    dateCreated: new Date('2024-06-15'),
    status: 'fresh',
    description: "Modular playpen for small pets",
    dateUpdated: new Date('2024-06-15'),
    imageUrls: ["https://picsum.photos/id/193/300/200"],
    discount: 0.35,
    isFeatured: true
  },
  {
    id: new ObjectId(),
    name: "Pet Nail Clippers",
    price: 19.95,
    dateCreated: new Date('2024-06-18'),
    status: 'pending',
    description: "Professional pet nail trimming set",
    dateUpdated: new Date('2024-06-18'),
    imageUrls: ["https://picsum.photos/id/1037/300/200"],
    discount: 0.0,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Dog Pool",
    price: 67.50,
    dateCreated: new Date('2024-06-20'),
    status: 'cancelled',
    description: "Inflatable swimming pool for dogs",
    dateUpdated: new Date('2024-06-21'),
    imageUrls: ["https://picsum.photos/id/1038/300/200"],
    discount: 0.25,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Bird Perch Stand",
    price: 89.99,
    dateCreated: new Date('2024-06-22'),
    status: 'fresh',
    description: "Free-standing play stand for birds",
    dateUpdated: new Date('2024-06-22'),
    imageUrls: ["https://picsum.photos/id/111/300/200"],
    discount: 0.2,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Pet Stain Remover",
    price: 27.75,
    dateCreated: new Date('2024-06-25'),
    status: 'completed',
    description: "Enzymatic cleaner for pet accidents",
    dateUpdated: new Date('2024-06-27'),
    imageUrls: ["https://picsum.photos/id/1039/300/200"],
    discount: 0.15,
    isFeatured: false
  },
  {
    id: new ObjectId(),
    name: "Cat Window Hammock",
    price: 42.50,
    dateCreated: new Date('2024-06-28'),
    status: 'pending',
    description: "Suction cup window hammock for cats",
    dateUpdated: new Date('2024-06-28'),
    imageUrls: ["https://picsum.photos/id/240/300/200"],
    discount: 0.4,
    isFeatured: true
  }
];